server:
  port: 8761 # 端口

spring:
  application:
    name: eureka-server # 应用名称

# 配置 Eureka Server 注册中心
eureka:
  instance:
    hostname: eureka01			  # 主机名，不配置的时候将根据操作系统的主机名来获取
    prefer-ip-address: true
  client:
     service-url:
#       register-with-eureka: false   # 是否将自己注册到注册中心，默认为 true
#       fetch-registry: false   # 注册中心对外暴露的注册地址
       defaultZone: http://localhost:8762/eureka/

      #    集群环境下需将自己注册