server:
  port: 7073 # 端口

spring:
  application:
    name: openfeign # 应用名称(集群下相同)

  # 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true       # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url: # 设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka/

# 配置日志
feign:
  hystrix:
    enabled: true
  compression:
    request: # 请求数据压缩
      enabled: true
      mime-types: text/html,application/json
      min-request-size: 2048 #压缩数据下限，表示当前传输的数据量大于2048需要压缩
    response:
      enabled: true # 响应数据压缩

