server:
  port: 8762 # 端口

spring:
  application:
    name: eureka-server # 应用名称

# 配置 Eureka Server 注册中心
eureka:
  instance:
    hostname: eureka02			  # 主机名，不配置的时候将根据操作系统的主机名来获取
    prefer-ip-address: true
  client:
#    集群环境下需将自己注册
    register-with-eureka: true   # 是否将自己注册到注册中心，默认为 true
    fetch-registry: true         # 是否从注册中心获取服务注册信息，默认为 true
    service-url:                  # 注册中心对外暴露的注册地址
      defaultZone: http://localhost:8761/eureka/